export interface BlogPost {
    id: string
    title: string
    excerpt: string
    content: string
    author: string
    date: string
    image: string
    category: string
    slug: string
}

export const blogPosts: BlogPost[] = [
    {
        id: "1",
        title: "Understanding Generic Medicines",
        excerpt: "Generic medicines are just as effective as brand-name medicines but cost significantly less. Learn more about how they work.",
        content: "Full content here...",
        author: "Dr. Sharma",
        date: "2023-10-15",
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800",
        category: "Education",
        slug: "understanding-generic-medicines",
    },
    {
        id: "2",
        title: "The Importance of Vaccination",
        excerpt: "Vaccines are crucial for preventing serious diseases. Discover why staying up-to-date with vaccinations is vital for public health.",
        content: "Full content here...",
        author: "Nurse Rina",
        date: "2023-11-02",
        image: "https://images.unsplash.com/photo-1633613286991-611fe299c4be?auto=format&fit=crop&q=80&w=800",
        category: "Health Awareness",
        slug: "importance-of-vaccination",
    },
    {
        id: "3",
        title: "Healthy Living Tips for Winter",
        excerpt: "Winter brings specific health challenges. Here are some tips to stay healthy and active during the colder months.",
        content: "Full content here...",
        author: "Wellness Team",
        date: "2023-12-01",
        image: "https://images.unsplash.com/photo-1516481265257-97e5f4bc50d5?auto=format&fit=crop&q=80&w=800",
        category: "Lifestyle",
        slug: "healthy-living-winter",
    }, {
        id: "1",
        title: "Understanding Generic Medicines",
        excerpt: "Generic medicines are just as effective as brand-name medicines but cost significantly less. Learn more about how they work.",
        content: "Full content here...",
        author: "Dr. Sharma",
        date: "2023-10-15",
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800",
        category: "Education",
        slug: "understanding-generic-medicines",
    },
    {
        id: "2",
        title: "The Importance of Vaccination",
        excerpt: "Vaccines are crucial for preventing serious diseases. Discover why staying up-to-date with vaccinations is vital for public health.",
        content: "Full content here...",
        author: "Nurse Rina",
        date: "2023-11-02",
        image: "https://images.unsplash.com/photo-1633613286991-611fe299c4be?auto=format&fit=crop&q=80&w=800",
        category: "Health Awareness",
        slug: "importance-of-vaccination",
    },
    {
        id: "3",
        title: "Healthy Living Tips for Winter",
        excerpt: "Winter brings specific health challenges. Here are some tips to stay healthy and active during the colder months.",
        content: "Full content here...",
        author: "Wellness Team",
        date: "2023-12-01",
        image: "https://images.unsplash.com/photo-1516481265257-97e5f4bc50d5?auto=format&fit=crop&q=80&w=800",
        category: "Lifestyle",
        slug: "healthy-living-winter",
    }, {
        id: "1",
        title: "Understanding Generic Medicines",
        excerpt: "Generic medicines are just as effective as brand-name medicines but cost significantly less. Learn more about how they work.",
        content: "Full content here...",
        author: "Dr. Sharma",
        date: "2023-10-15",
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800",
        category: "Education",
        slug: "understanding-generic-medicines",
    },
    {
        id: "2",
        title: "The Importance of Vaccination",
        excerpt: "Vaccines are crucial for preventing serious diseases. Discover why staying up-to-date with vaccinations is vital for public health.",
        content: "Full content here...",
        author: "Nurse Rina",
        date: "2023-11-02",
        image: "https://images.unsplash.com/photo-1633613286991-611fe299c4be?auto=format&fit=crop&q=80&w=800",
        category: "Health Awareness",
        slug: "importance-of-vaccination",
    },
    {
        id: "3",
        title: "Healthy Living Tips for Winter",
        excerpt: "Winter brings specific health challenges. Here are some tips to stay healthy and active during the colder months.",
        content: "Full content here...",
        author: "Wellness Team",
        date: "2023-12-01",
        image: "https://images.unsplash.com/photo-1516481265257-97e5f4bc50d5?auto=format&fit=crop&q=80&w=800",
        category: "Lifestyle",
        slug: "healthy-living-winter",
    }, {
        id: "1",
        title: "Understanding Generic Medicines",
        excerpt: "Generic medicines are just as effective as brand-name medicines but cost significantly less. Learn more about how they work.",
        content: "Full content here...",
        author: "Dr. Sharma",
        date: "2023-10-15",
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800",
        category: "Education",
        slug: "understanding-generic-medicines",
    },
    {
        id: "2",
        title: "The Importance of Vaccination",
        excerpt: "Vaccines are crucial for preventing serious diseases. Discover why staying up-to-date with vaccinations is vital for public health.",
        content: "Full content here...",
        author: "Nurse Rina",
        date: "2023-11-02",
        image: "https://images.unsplash.com/photo-1633613286991-611fe299c4be?auto=format&fit=crop&q=80&w=800",
        category: "Health Awareness",
        slug: "importance-of-vaccination",
    },
    {
        id: "3",
        title: "Healthy Living Tips for Winter",
        excerpt: "Winter brings specific health challenges. Here are some tips to stay healthy and active during the colder months.",
        content: "Full content here...",
        author: "Wellness Team",
        date: "2023-12-01",
        image: "https://images.unsplash.com/photo-1516481265257-97e5f4bc50d5?auto=format&fit=crop&q=80&w=800",
        category: "Lifestyle",
        slug: "healthy-living-winter",
    }, {
        id: "1",
        title: "Understanding Generic Medicines",
        excerpt: "Generic medicines are just as effective as brand-name medicines but cost significantly less. Learn more about how they work.",
        content: "Full content here...",
        author: "Dr. Sharma",
        date: "2023-10-15",
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800",
        category: "Education",
        slug: "understanding-generic-medicines",
    },
    {
        id: "2",
        title: "The Importance of Vaccination",
        excerpt: "Vaccines are crucial for preventing serious diseases. Discover why staying up-to-date with vaccinations is vital for public health.",
        content: "Full content here...",
        author: "Nurse Rina",
        date: "2023-11-02",
        image: "https://images.unsplash.com/photo-1633613286991-611fe299c4be?auto=format&fit=crop&q=80&w=800",
        category: "Health Awareness",
        slug: "importance-of-vaccination",
    },
    {
        id: "3",
        title: "Healthy Living Tips for Winter",
        excerpt: "Winter brings specific health challenges. Here are some tips to stay healthy and active during the colder months.",
        content: "Full content here...",
        author: "Wellness Team",
        date: "2023-12-01",
        image: "https://images.unsplash.com/photo-1516481265257-97e5f4bc50d5?auto=format&fit=crop&q=80&w=800",
        category: "Lifestyle",
        slug: "healthy-living-winter",
    }, {
        id: "1",
        title: "Understanding Generic Medicines",
        excerpt: "Generic medicines are just as effective as brand-name medicines but cost significantly less. Learn more about how they work.",
        content: "Full content here...",
        author: "Dr. Sharma",
        date: "2023-10-15",
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800",
        category: "Education",
        slug: "understanding-generic-medicines",
    },
    {
        id: "2",
        title: "The Importance of Vaccination",
        excerpt: "Vaccines are crucial for preventing serious diseases. Discover why staying up-to-date with vaccinations is vital for public health.",
        content: "Full content here...",
        author: "Nurse Rina",
        date: "2023-11-02",
        image: "https://images.unsplash.com/photo-1633613286991-611fe299c4be?auto=format&fit=crop&q=80&w=800",
        category: "Health Awareness",
        slug: "importance-of-vaccination",
    },
    {
        id: "3",
        title: "Healthy Living Tips for Winter",
        excerpt: "Winter brings specific health challenges. Here are some tips to stay healthy and active during the colder months.",
        content: "Full content here...",
        author: "Wellness Team",
        date: "2023-12-01",
        image: "https://images.unsplash.com/photo-1516481265257-97e5f4bc50d5?auto=format&fit=crop&q=80&w=800",
        category: "Lifestyle",
        slug: "healthy-living-winter",
    }, {
        id: "1",
        title: "Understanding Generic Medicines",
        excerpt: "Generic medicines are just as effective as brand-name medicines but cost significantly less. Learn more about how they work.",
        content: "Full content here...",
        author: "Dr. Sharma",
        date: "2023-10-15",
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800",
        category: "Education",
        slug: "understanding-generic-medicines",
    },
    {
        id: "2",
        title: "The Importance of Vaccination",
        excerpt: "Vaccines are crucial for preventing serious diseases. Discover why staying up-to-date with vaccinations is vital for public health.",
        content: "Full content here...",
        author: "Nurse Rina",
        date: "2023-11-02",
        image: "https://images.unsplash.com/photo-1633613286991-611fe299c4be?auto=format&fit=crop&q=80&w=800",
        category: "Health Awareness",
        slug: "importance-of-vaccination",
    },
    {
        id: "3",
        title: "Healthy Living Tips for Winter",
        excerpt: "Winter brings specific health challenges. Here are some tips to stay healthy and active during the colder months.",
        content: "Full content here...",
        author: "Wellness Team",
        date: "2023-12-01",
        image: "https://images.unsplash.com/photo-1516481265257-97e5f4bc50d5?auto=format&fit=crop&q=80&w=800",
        category: "Lifestyle",
        slug: "healthy-living-winter",
    }, {
        id: "1",
        title: "Understanding Generic Medicines",
        excerpt: "Generic medicines are just as effective as brand-name medicines but cost significantly less. Learn more about how they work.",
        content: "Full content here...",
        author: "Dr. Sharma",
        date: "2023-10-15",
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800",
        category: "Education",
        slug: "understanding-generic-medicines",
    },
    {
        id: "2",
        title: "The Importance of Vaccination",
        excerpt: "Vaccines are crucial for preventing serious diseases. Discover why staying up-to-date with vaccinations is vital for public health.",
        content: "Full content here...",
        author: "Nurse Rina",
        date: "2023-11-02",
        image: "https://images.unsplash.com/photo-1633613286991-611fe299c4be?auto=format&fit=crop&q=80&w=800",
        category: "Health Awareness",
        slug: "importance-of-vaccination",
    },
    {
        id: "3",
        title: "Healthy Living Tips for Winter",
        excerpt: "Winter brings specific health challenges. Here are some tips to stay healthy and active during the colder months.",
        content: "Full content here...",
        author: "Wellness Team",
        date: "2023-12-01",
        image: "https://images.unsplash.com/photo-1516481265257-97e5f4bc50d5?auto=format&fit=crop&q=80&w=800",
        category: "Lifestyle",
        slug: "healthy-living-winter",
    }, {
        id: "1",
        title: "Understanding Generic Medicines",
        excerpt: "Generic medicines are just as effective as brand-name medicines but cost significantly less. Learn more about how they work.",
        content: "Full content here...",
        author: "Dr. Sharma",
        date: "2023-10-15",
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800",
        category: "Education",
        slug: "understanding-generic-medicines",
    },
    {
        id: "2",
        title: "The Importance of Vaccination",
        excerpt: "Vaccines are crucial for preventing serious diseases. Discover why staying up-to-date with vaccinations is vital for public health.",
        content: "Full content here...",
        author: "Nurse Rina",
        date: "2023-11-02",
        image: "https://images.unsplash.com/photo-1633613286991-611fe299c4be?auto=format&fit=crop&q=80&w=800",
        category: "Health Awareness",
        slug: "importance-of-vaccination",
    },
    {
        id: "3",
        title: "Healthy Living Tips for Winter",
        excerpt: "Winter brings specific health challenges. Here are some tips to stay healthy and active during the colder months.",
        content: "Full content here...",
        author: "Wellness Team",
        date: "2023-12-01",
        image: "https://images.unsplash.com/photo-1516481265257-97e5f4bc50d5?auto=format&fit=crop&q=80&w=800",
        category: "Lifestyle",
        slug: "healthy-living-winter",
    },
]
